/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Gradledemo;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class Library{

	public static void main(String[] args) {
		
System.setProperty("webdriver.chrome.driver","C://Users//BLTuser.BLT1218//Downloads//chromedriver_win32//chromedriver.exe");
WebDriver driver=new ChromeDriver();
driver.get("https://www.linkedin.com");
}
}